import { faker } from "@faker-js/faker";
import { Program } from "./types";

const getUuid = () => faker.string.uuid();
export const myStaticProgram: Program = {
    name: "prastoin's program",
    sessionList: [
        {
            name: "Bench press day",
            uuid: getUuid(),
            exerciseList: [
                {
                    name: "Bench press barbell",
                    load: 80,
                    rep: 8,
                    rest: 230,
                    set: 4,
                    uuid: getUuid(),
                    targetMuscle: ["Chest", "Triceps"],
                },
                {
                    name: "Vertical pulldown",
                    load: 70,
                    rep: 8,
                    rest: 230,
                    set: 4,
                    uuid: getUuid(),
                    targetMuscle: ["Lats", "Biceps"],
                },
                {
                    name: "Leg extension",
                    load: 70,
                    rep: 8,
                    rest: 230,
                    set: 4,
                    uuid: getUuid(),
                    targetMuscle: ["Quadriceps"],
                },
                {
                    name: "Lateral raises cable",
                    load: 5,
                    rep: 10,
                    rest: 130,
                    set: 4,
                    uuid: getUuid(),
                    targetMuscle: ["Deltoid"],
                },
                {
                    name: "Biceps curl db",
                    load: 12,
                    rep: 8,
                    rest: 200,
                    set: 4,
                    uuid: getUuid(),
                    targetMuscle: ["Biceps"],
                },
            ],
        },
        {
            name: "Squat day",
            uuid: getUuid(),
            exerciseList: [
                {
                    name: "Squat barbell",
                    load: 80,
                    rep: 8,
                    rest: 230,
                    set: 4,
                    uuid: getUuid(),
                    targetMuscle: ["Quadriceps", "Glutes", "Harmstring"],
                },
                {
                    name: "Overhead press machine",
                    load: 50,
                    rep: 8,
                    rest: 230,
                    set: 4,
                    uuid: getUuid(),
                    targetMuscle: ["Deltoid"],
                },
                {
                    name: "Rear delt cable",
                    load: 5,
                    rep: 10,
                    rest: 130,
                    set: 4,
                    uuid: getUuid(),
                    targetMuscle: ["Deltoid"],
                },
                {
                    name: "Assisted pullups",
                    load: -21,
                    rep: 6,
                    rest: 200,
                    set: 4,
                    uuid: getUuid(),
                    targetMuscle: ["Lats", "Biceps"],
                },
                {
                    name: "Biceps curl barbell",
                    load: 33,
                    rep: 8,
                    rest: 200,
                    set: 4,
                    uuid: getUuid(),
                    targetMuscle: ["Biceps"],
                },
            ],
        },
        {
            name: "Low row day",
            uuid: getUuid(),
            exerciseList: [
                {
                    name: "Low row machine 1 by 1",
                    load: 40,
                    rep: 8,
                    rest: 130,
                    set: 4,
                    uuid: getUuid(),
                    targetMuscle: ["Back"],
                },
                {
                    name: "Incline dumbell bench press",
                    load: 32,
                    rep: 8,
                    rest: 230,
                    set: 4,
                    uuid: getUuid(),
                    targetMuscle: ["Chest", "Triceps"],
                },
                {
                    name: "Cable Y",
                    load: 3.75,
                    rep: 10,
                    rest: 130,
                    set: 4,
                    uuid: getUuid(),
                    targetMuscle: ["Deltoid"],
                },
                {
                    name: "Triceps ropes",
                    load: 17.5,
                    rep: 8,
                    rest: 200,
                    set: 4,
                    uuid: getUuid(),
                    targetMuscle: ["Triceps"],
                },
                {
                    name: "Calves raises",
                    load: 60,
                    rep: 8,
                    rest: 200,
                    set: 4,
                    uuid: getUuid(),
                    targetMuscle: ["Calves"],
                },
            ],
        },
        {
            name: "Conventional Deadlift day",
            uuid: getUuid(),
            exerciseList: [
                {
                    name: "Conventional Deadlift day",
                    load: 110,
                    rep: 8,
                    rest: 230,
                    set: 4,
                    uuid: getUuid(),
                    targetMuscle: ["Glutes", "Harmstring", "Forearm", "Glutes"],
                },
                {
                    name: "Leg curl",
                    load: 40,
                    rep: 8,
                    rest: 200,
                    set: 4,
                    uuid: getUuid(),
                    targetMuscle: ["Harmstring"],
                },
                {
                    name: "Trieps barbell",
                    load: 25,
                    rep: 8,
                    rest: 200,
                    set: 4,
                    uuid: getUuid(),
                    targetMuscle: ["Triceps"],
                },
                {
                    name: "Butterfly",
                    load: 60,
                    rep: 8,
                    rest: 200,
                    set: 4,
                    uuid: getUuid(),
                    targetMuscle: ["Chest"],
                },
            ],
        },
    ],
    uuid: "42",
};
